name: Build and Test Documentation

on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main

jobs:

  test-docs:
    runs-on: ubuntu-latest

    steps:

    - name: Checkout
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r docs/requirements.txt

    - name: Build documentation
      run: |
        sphinx-build -b html docs/ docs/_build/html

    - name: Documentation tests
      run: |
        sphinx-build -W --keep-going -b spelling docs/ docs/_build/spelling
